import { ThemeSwitch } from "@/components";
import ThemeContextProvider from "@/context/theme-context";
import "@/styles/globals.scss";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["400", "600"]
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={
        `${poppins.variable} 
        bg-gray-50
        text-gray-950
        dark:bg-gray-900
        dark:text-gray-50`
      }>
           <ThemeContextProvider>
            <ThemeSwitch />
            <div className="max-w-screen-lg p-16 m-auto">
                {[children]}
            </div>
           </ThemeContextProvider>
        </body>
    </html>
  );
}
